# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-11 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event_reminder',
            name='event_date',
            field=models.DateField(blank=True, help_text='month/day/year', null=True),
        ),
    ]
